export enum ResourceState {
  TERMINATED = 'terminated',
  UPDATING = 'updating',
  READY = 'ready',
  COMPLETED = 'completed',
  ABNORMAL = 'abnormal',
  FAILED = 'failed',
  SUSPENDED = 'suspended',
  RUNNING = 'running',
  SUCCEEDED = 'succeeded',
  UNKNOWN = 'unknown',
  TERMINATING = 'terminating',
  PENDING = 'pending',
  WAITING = 'waiting',
  STOPPED = 'stopped',
  AVAILABLE = 'available',
  BOUND = 'bound',
  RELEASED = 'released',
  LOST = 'lost',
  ACTIVE = 'active',
  DELETING = 'deleting',
}

